
FROM infragravity/nanoserver-iis:0.0.3
LABEL Name=infragravity/sonar-samples-webapi Version=0.0.1 
LABEL Maintainer=info@infragravity.com

ENV SONAR_DOWNLOAD_URL http://www.infragravity.com/download/sonar-d-0180-win10-x64
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Invoke-WebRequest http://www.infragravity.com/download/sonar-d-0180-win10-x64 -OutFile Sonar.zip
RUN Expand-Archive Sonar.zip -DestinationPath \sonar
WORKDIR /out
COPY ./out .
ADD ./out/Sonard.config c:/sonar
ADD ./out/Sonard.dll.config c:/sonar/out
ADD ./lib/ServiceMonitor.exe c:/ServiceMonitor.exe
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN New-IISSite -Name "AspNetCore" -PhysicalPath c:\out\ -BindingInformation "*:8000:"
RUN Set-WSManInstance WinRM/Config/Service -ValueSet @{AllowUnencrypted=\"true\"}
RUN sc.exe create sonard binpath= c:\sonar\out\Sonard.exe start= auto obj= LocalSystem depend= \"WinRM\"
ENTRYPOINT ["C:\\ServiceMonitor.exe", "w3svc"]
